further fix autoconf ....

diff --git a/tools/autoconf b/tools/autoconf
--- a/tools/autoconf
+++ b/tools/autoconf
@@ -20,7 +20,7 @@ echo ">> Program to install: $PROG_NAME"
 TMPDIR=$(mktemp -d)
 
 # check if git command exists or not
-if type "$CMD_NAME" >> "/dev/null"; then
+if type "$CMD_NAME" &> /dev/null; then
     echo "You already have $PROG_NAME installed"
     while true; do
         read -p "Do you wish to install $CUR_VERSION of this program?[y/N] " yn
@@ -43,8 +43,8 @@ TARDIR="$TMPDIR/$(tar -tzf $PROG_LOC | head -1 | cut -f1 -d'/')"
 tar -xzf "$PROG_LOC" -C "$TMPDIR"
 
 # steps from https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
-(cd "$TARDIR" && exec configure") || { echo "./configure failed"; exit 1; }
-make -C "$TARDIR" || { echo "make failed"; exit 1; }
-make -C "$TARDIR" install || { echo "make install failed"; exit 1; }
+(cd "$TARDIR" && exec configure) || { echo './configure failed'; exit 1; }
+make -C "$TARDIR" || { echo 'make failed'; exit 1; }
+make -C "$TARDIR" install || { echo 'make install failed'; exit 1; }
 
-echo ">> Installation complete!"
+echo '>> Installation complete!'
