remove info from git

diff --git a/tools/git b/tools/git
--- a/tools/git
+++ b/tools/git
@@ -52,7 +52,7 @@ if ! type "autoconf" &> /dev/null; then
 fi
 make -C "$TARDIR" configure || { echo "make configure failed"; exit 1; }
 "$TARDIR/configure" --prefix=/usr
-make -C "$TARDIR" all doc info || { echo "make all doc info failed"; exit 1; }
-make -C "$TARDIR" install install-doc install-html install-info || { echo "make install install-doc install-html install-info failed"; exit 1; }
+make -C "$TARDIR" all doc || { echo "make all doc info failed"; exit 1; }
+make -C "$TARDIR" install install-doc install-html || { echo "make install install-doc install-html install-info failed"; exit 1; }
 
 echo '>> Installation complete!'
