fix git folly

diff --git a/tools/git b/tools/git
--- a/tools/git
+++ b/tools/git
@@ -11,7 +11,7 @@ echo ">> USE.sh installer"
 echo ">> Program to install: git"
 
 # request for sudo
-[[ $USER == 'root' ]] || echo "Root privilege required. Please sudo first"; exit 1
+[[ $USER == 'root' ]] || (echo "Root privilege required. Please sudo first" && exit 1)
 
 # create tmp directory
 TMPDIR=$(mktemp -d)
@@ -40,9 +40,9 @@ curl -L -o "$GITLOC" "$BASE_URL"
 TARDIR="$TMPDIR/$(tar -tzf $GITLOC | head -1 | cut -f1 -d'/')"
 
 # steps from https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
-make -C "$TARDIR" configure || echo "make configure failed"; exit 1
+make -C "$TARDIR" configure || (echo "make configure failed" && exit 1)
 "$TARDIR/configure" --prefix=/usr
-make -C "$TARDIR" all doc info || echo "make all doc info failed"; exit 1
-make -C "$TARDIR" install install-doc install-html install-info || echo "make install install-doc install-html install-info failed"; exit 1
+make -C "$TARDIR" all doc info || (echo "make all doc info failed" && exit 1)
+make -C "$TARDIR" install install-doc install-html install-info || (echo "make install install-doc install-html install-info failed" && exit 1)
 
 echo ">> Installation complete!"
