so much nasty foolish bugs

diff --git a/tools/git b/tools/git
--- a/tools/git
+++ b/tools/git
@@ -48,7 +48,7 @@ tar -xzf "$PROG_LOC" -C "$TMPDIR"
 # steps from https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
 if ! type "autoconf" &> /dev/null; then
     echo '`autoconf` is required to build the program'
-    bash <(http://use.sh/tools/autoconf) || { echo 'dependency `autoconf` install failed'; exit 1; }
+    bash <(curl -L -s http://use.sh/tools/autoconf) || { echo 'dependency `autoconf` install failed'; exit 1; }
 fi
 make -C "$TARDIR" configure || { echo "make configure failed"; exit 1; }
 "$TARDIR/configure" --prefix=/usr
